ATTENTION_V18_RULES = """V18 five-test decision-closure contract. This replaces the accumulated V13/V14/V16/V17 first-pass calibration stack with one ordered proof procedure. It preserves the existing five review-worthiness tests, eligible evidence surfaces, canonicalization behavior, and frozen product gates.
Ordered closure rule: before deciding, identify exactly one candidate governing mechanism and then evaluate the five existing tests in this order: mechanism, review-span, review-leverage, durable-knowledge, boundary-effect. Each test needs its own direct witness in the current packet. A fact that helps one test does not satisfy another merely because the prose sounds contract-like. If any required witness is absent, outside the packet, inferred, or only a plausible downstream consequence, decline. Choose interpretation type only after all five tests pass. Type labels, mechanism wording, uncertainty notes, persistence, cross-file breadth, test names, comments, or likely callers cannot rescue a missing conjunct.
Mechanism closure rule: remove repository-specific nouns, file and symbol names, transport or storage carriers, UI labels, test structure, and implementation technique from the candidate mechanism. What remains must still be reusable governing knowledge that a future reviewer, operator, or implementer must preserve. If it collapses to validation shape, routing, source selection, helper or callback ownership, local cleanup, retry or timeout policy, caching, presentation, registration, configuration choice, bookkeeping, or another single-execution implementation technique, decline unless the packet directly proves a qualifying governing span and changed consequential outcome.
Review-span closure rule: directly establish at least one review-bearing span already allowed by the base rubric: a stable trust/authority rule across distinct principals or trust domains; a durable lifecycle crossing an independent invocation, restart, migration, recovery, deletion/re-admission, participant, or later phase; a cross-boundary failure/recovery handoff or multi-step/multi-participant correctness invariant; an externally consumed support, compatibility, classification, taxonomy, or operator-control contract; or the existing direct consumer/operator read-action lifecycle. Multiple files, layers, callbacks, routes, persisted values, or APIs do not establish a span by themselves. For the direct consumer/operator exception, the packet itself must directly show the same consumer surface observing governed state and performing the governed transition, with the observed state governing subsequent eligibility, required action, terminal/recovery status, or another non-local decision outcome. When that relationship is directly evidenced, do not require separate producer, storage, or persistence implementation bytes merely to restate it. Read-only mirrors, write-only wrappers, ordinary CRUD/editor surfaces, presentation-only surfaces, and unrelated reads and writes do not qualify on that basis.
Review-leverage closure rule: directly establish that the governing contract itself is new or materially changed, or that a changed enforcement mechanism introduces or materially changes a reusable fail-closed, recovery, terminal, migration, re-admission, trust-boundary, or cross-boundary/multi-step correctness rule by which that contract is upheld. Newly added verification, examples, fixtures, comments, documentation, or expectations do not prove changed governing behavior when the authoritative behavior and changedness remain outside the packet. Preserve the existing eligible exceptions: an authoritative changed project-state declaration may itself be the changed contract, and an end-to-end behavioral test may establish leverage when it directly exercises the qualifying sides and changed outcome. A repair that merely restores an already-declared obligation is not leverage unless the packet directly establishes a changed durable governing enforcement rule future implementations must preserve.
Durable-knowledge closure rule: after removing commit-specific wording and implementation technique, the packet must still answer a stable question about authority, durable lifecycle state, externally consumed support/compatibility/classification/operator control, cross-boundary failure or terminal disposition, or multi-step/multi-participant correctness. Persistence, a schema field, function, callback, command, internal API, status label, generated projection, or an interface with an unseen caller is not durable knowledge by itself. A changed interface may qualify only when the interface itself is an externally consumed authoritative contract under the five tests or when the consuming side is directly evidenced.
Boundary-effect closure rule: directly show the consequential contract outcome that corresponds to the qualifying span: authority exercised or denied across a trust boundary; durable state admitted, preserved, removed, migrated, recovered, re-admitted, or made visible to a later independent lifecycle; externally consumed support, compatibility, classification, operator control, or decision semantics; a cross-boundary failure/recovery or terminal outcome; a governed consumer state/action transition; or a multi-step/multi-participant invariant preserving coherent externally or durably consumed state. A declaration that an unseen actor, caller, consumer, executor, operator, or later phase will use something does not prove that participant or its consequential outcome. Uncertainty may describe non-required details but cannot fill a missing required participant, changedness fact, handoff, lifecycle phase, or boundary effect.
Evidence-role closure rule: all evidence surfaces remain eligible under the existing rubric. StructuralDelta and SourceAssertion evidence may directly prove what they actually establish; a SourceAssertion may itself be authoritative when its source is the changed project-state contract. Tests, documentation, generated surfaces, translations, migrations, plans, fixtures, harnesses, workflows, configuration, and examples remain weak priors rather than hard suppression categories. They qualify only when their own changed content directly establishes all five tests, not when they merely describe or verify unseen governing behavior. Direct structural or behavioral packet evidence does not need to be exercised by a test or live execution merely to remain eligible, and eligible tests or documents do not require runtime implementation bytes when the evidence surface itself directly proves the governing contract and boundary effect.
Type-closure rule: select a canonical interpretation type only after all five tests pass, and do not use a type to manufacture eligibility. authority_governance requires directly evidenced distinct principals or trust domains plus the capability or credential relation that crosses, is delegated across, or is denied across that boundary. failure requires a changed durable terminal disposition or a changed cross-boundary recovery handoff that a separate phase, participant, consumer, or operator must rely on. temporal_correctness requires independently progressing actors, tasks, processes, devices, or lifecycle epochs plus a directly evidenced timing/conflict relation capable of changing a durable or external outcome. project_state requires an authoritative changed support, compatibility, governance, schema-consumer, or declared project-state contract relied on by an external consumer/operator or later lifecycle phase. Use generic introduction or modification only when no more specific qualifying type governs the contract.
Facet and canonicalization closure rule: storage, service, consumer/UI, adapter, documentation, tests, migrations, generated projections, and other facets of one governing mechanism should converge on the same short rule-level label and canonical type when each packet directly proves that mechanism. A subordinate facet that merely implements, verifies, mirrors, migrates, documents, presents, or exposes a broader rule without independently proving all five tests must decline rather than become a parallel review item. Do not broaden several unrelated minor changes into one mechanism.
Human-attention closure rule: interpret only reusable governing knowledge worth preserving across independent execution or lifecycle boundaries. A change being real, useful, externally visible, security-adjacent, persistent, cross-file, or well tested is not sufficient. Silence is valid when the packet does not close all five tests.
"""

REPAIR_V15_RULES = """V15 provider-output repair reliability clarification. These rules apply only after a provider response has already failed deterministic parsing or validation. They do not change the five review-worthiness tests, evidence eligibility, canonicalization, or any frozen product gate.
Serialization rule: emit exactly one compact single-line JSON object with no markdown, commentary, code fence, trailing text, or literal control characters inside string values. Use normal JSON escaping for quotation marks, backslashes, and embedded control characters. Complete every opened string, array, and object before returning.
Malformed-output reconstruction rule: when the rejected provider response is not parseable JSON, reconstruct a fresh response from the CandidateEvidencePacket and deterministic repair context. Do not continue, splice, quote, or imitate malformed or apparently truncated raw output.
Support-copy rule: every support object must be copied character-for-character from the supplied exact semantic support choices or exact support allowlist. Do not derive, regenerate, shorten, complete, or infer an identifier from evidence prose, hashes, neighboring packets, repository familiarity, or a previous rejected output. Prefer the smallest sufficient support set and exactly one semantic support when one is sufficient.
Semantic-lock serialization rule: when semantic_reference is supplied, preserve every supplied non-support semantic field exactly and perform only JSON serialization plus exact support selection. Do not paraphrase the preserved mechanism, summary, interpretation types, or uncertainty notes.
Repair-economy rule: when no semantic_reference exists, keep repaired prose concise and limited to what is necessary to satisfy the unchanged output contract and evidence-grounding requirements. Do not repeat the packet, narrate the repair process, or add explanatory material outside the JSON fields.
Fail-closed rule: if a valid exact semantic support cannot be selected without changing a preserved interpretation, keep decision=interpret with an empty supports array so deterministic validation rejects the repair. Never convert a supported interpretation to decline merely to make serialization easier.
"""
